project: vq_vae_sem_2
entity: deya-03-the-university-of-manchester
program: /share/nas2_3/adey/astro/clean_code/Neural-Compression-for-Radio-Astronomy/vae/main_vae.py  # Path to your main Python script

metric:
  name: train/total_loss_per_100
  goal: minimize
method: grid
parameters:
  latent_dim:
    #min: 8  
    #max: 384 
    #distribution: int_uniform  
    values: [64,64,64,64]
max_runs: 50  
parameter_constraints:
  - "(latent_dim * log2(latent_dim)) <= 3072"